### ISSUE TITLE
live-installer: non-latin keyboard should be added, not set.

### ISSUE THREAD

**Issue by Chocobo-ts** [linuxmint/lmde-3-cinnamon-beta#10]
When user choose keyboard layout in installer - it will be immediately  registered setxkb as only one layout in live system and as only one layout for target system.

For non-latin layouts - this results in cannot continue installation because username cannot consist of cyrillic symbols, for example

`mint@mint:~$ setxkbmap -query
rules: evdev
model: pc105
layout: ru
options: terminate:ctrl_alt_bksp`

if after that user manually change layout config to both english+cyrillic and continue installation,  in the case an password will contain latin symbols - at  the first reboot to installed OS he is can not login because only one available layout will be non latin without possibility to change it

this behaviour must add a selected layout as additional to the default en_US layout, and add a toggle hotkey for changing it

https://linuxmint.com.ru/viewtopic.php?p=58100#p58100 - screenshots with comments (on Russian)
This issue was also affected LMDE2 Betsy, all these years( 

Fix, please

**Comment by clefebvre** [comment]
Hi @Chocobo-ts,

You mentioned this affected Ubiquity in Mint/Ubuntu as well?

Can you confirm this also affects live-installer in LMDE 3?

**Comment by clefebvre** [comment]
https://github.com/linuxmint/live-installer/issues/23

@monsta

**Comment by monsta** [comment]
Well, I can't add anything more besides what I've said in https://github.com/linuxmint/live-installer/issues/23 :slightly_smiling_face:

**Comment by Chocobo-ts** [comment]
@clefebvre Yes, I checked it and now confirm this. Issue equally  affects  live-installer/calamares in LMDE3 Cindy and live-installer in LMDE2 Betsy. 

Ubiquity installer in Ubuntu-based LM editions - doesn't have this problem.

@monsta, Hi! As possible way to fix it - in the past year I edit source  gtk_interface.py and installer.py in live-installer LMDE2,  with simple fix an adding en_US layout when setxkbmap calls by live-installer. 
https://linuxmint.com.ru/viewtopic.php?t=1622 - please look at it, hope this can help

Maybe for the universality it will need additional statement condition, some like this:
`if choised latin: 
   do nothing; 
elif choised non-latin: 
  do non-latin + en_US + alt_shift_toggle`; 

Thanks!

**Comment by monsta** [comment]
Well, my Python knowledge is very limited :slightly_smiling_face: 
If you can, please make a pull request, and @clefebvre will review it.

**Comment by Chocobo-ts** [comment]
I can try, but i'm not a programmer :)
just linux engineer, who can read the python-code...

**Comment by Chocobo-ts** [comment]
After a long search, i'm find a method how it implemented in ubiquity from ubuntu-based LM :)

https://pastebin.com/yHp5XwQk

And now we need to adapt  it for live-installer and calamares)

**Comment by Chocobo-ts** [comment]
I'm prepare and check PR for live-installer, please check it
https://github.com/linuxmint/live-installer/pull/89
https://github.com/linuxmint/live-installer/pull/88

**Comment by Chocobo-ts** [comment]
I have no idea how to make similar changes for calamares :(
С++ not for me

**Comment by clefebvre** [comment]
Cool, thanks for the PR @Chocobo-ts.

For calamares, I'd recommend to report is an issue on their github repo.

**Comment by clefebvre** [comment]
For ubiquity, we can try to patch it ourselves for Mint 19.1.

If you can report it upstream to Ubuntu on launchpad also, it would be good for them to fix it upstream as well.

**Comment by Chocobo-ts** [comment]
@clefebvre sorry, I may have mislead you about ubiquity in first message. 
I thought that live-installer is based on ubiquity code, but it is not. 

Bug only appears in LMDE installers, both live-installer and calamares. Ubuntu-based LM  do it properly.

**Comment by clefebvre** [comment]
Ah :) no pb.

**Comment by clefebvre** [comment]
@Chocobo-ts, @monsta,

Here's a build with the fixes. Can you test and confirm everything is fine?

[live-installer.zip](https://github.com/linuxmint/lmde-3-cinnamon-beta/files/2260298/live-installer.zip)

**Comment by monsta** [comment]
Oh nice :slightly_smiling_face: 

Found a few things though...
- some Cyrillic layouts are still applied w/o adding US layout + switch hotkey:
  - Kyrgyz
  - Montenegrin (Cyrillic - second subtype)
  - Serbian (Cyrillic variants)
- when choosing a layout which has additional US layout, the keyboard picture in the middle of the window always shows US layout
- actually, it also doesn't auto-switch to the chosen layout in the test field, need to press Alt-Shift to switch manually
- the last chosen layout stays in the system after quitting the installer, I think it should be reset to the default (US)

**Comment by clefebvre** [comment]
Another issue... Alt+tab is used for switching windows, Alt+Shift+Tab to switch windows the other way... setting Alt+Switch for keyboard layouts breaks reverse alt tab in Cinnamon.

**Comment by Chocobo-ts** [comment]
@clefebvre Thanks, it works!
About Alt+Shift+Tab - it's look as shared issue for any cinnamon installation) Alt+shift+tab also not work on LM19  with this default layout switch hotkey.
And furthermore, it's the first time I've ever heard this feature reverse switching windows  in cinnamon :) Probably it conflicts a very long time, alt+shift is a really default and most frequent hotkey for layouts(

@monsta 
**" it also doesn't auto-switch to the chosen layout in the test field, need to press Alt-Shift to switch manually"** 
We can symply fix it with replace the order in setxkbmap call, from "us,%s" to "%s, us" 

**"the last chosen layout stays in the system after quitting the installer,"** - I think it's a normal behavoir, because user has chosen the layouts he needs for session

**Comment by clefebvre** [comment]
we can't use %s,us... we want us in the next page for username etc.. and in DM by default.

I added fixes and more info in the UI in my commits today. I also switched to a new shortcut: Ctrl+Ctrl :)

**Comment by clefebvre** [comment]
Here's the new installer:

[live-installer.zip](https://github.com/linuxmint/lmde-3-cinnamon-beta/files/2262836/live-installer.zip)

This time around it makes it explicit en_US is added and tells you about the shortcut. I also removed the addition of "us," in installer.py (it's already added to self.setup.keyboard_layout in gtk_interface.py).

**Comment by clefebvre** [comment]
Don't hesitate to test it as much as possible. The code changes are a little heavy, so it's possible I might have introduced regressions.

**Comment by Chocobo-ts** [comment]
@clefebvre as I'm audit the code before - gtk_intergace.py change it for current live session, 
installer.py  - write chosen layout for a target system. I do not think that code must be excluded.

Now i will test last fixed installer and report it result here)

**Comment by Chocobo-ts** [comment]
@clefebvre and again about alt+shift+tab - this is bug in new Xorg as here - 
https://github.com/linuxmint/Cinnamon/issues/7664
https://bugzilla.freedesktop.org/show_bug.cgi?id=865

Affects LM19 and LMDE3, earlier versions works fine

**Comment by Chocobo-ts** [comment]
@clefebvre 
I confirm, latest build of installer with ctrl+ctrl work properly :+1:

**Comment by clefebvre** [comment]
Cool. Marking this issue as fixed then. Many thanks for your help guys.

**Comment by monsta** [comment]
Cool. I couldn't test two Ctrls switch in Virtualbox as it grabs right Ctrl for special shortcuts...

Does it also work properly in the installed system?

**Comment by monsta** [comment]
About Alt-Shift issue - looks like it affects Ctrl-Shift as well?
We have some downstream bug reports on that:

https://bugs.debian.org/891915
https://bugs.launchpad.net/bugs/1683383

The report on LP is even linked to that freedesktop report.
