### ISSUE TITLE
Unable to install dropbox

### ISSUE THREAD

**Issue by ghost** [linuxmint/lmde-3-cinnamon-beta#11]
- 'apt install dropbox' gives a 'E: Package 'dropbox' has no installation candidate'
- the 'flatpak' version does not install -> 'Error: Connection Reset by Peer'

**Comment by xenopeek** [comment]
Caja, Nautilus, Nemo and Thunar have plugin packages that depend on dropbox but indeed that package is missing from the import repository.

Until it's determined whether something can be done about that, the Flatpak install _should_ work. I was able to install without problems with this command:

`flatpak install flathub com.dropbox.Client`

The first Flatpak you install likely will be a huge download as it will commonly install a runtime (Dropbox requires the Gnome runtime, which on its own is 266 MiB download). The "connection reset by peer" may happen when Flathub server sees heavy use.

**Comment by kbd47** [comment]
Flatpack does not work. It installs but doesn't load during bootup. Install Dropbox from the Dropbox download web site, then let gdebi install it. Dropbox is working and loading during bootup for me now.

**Comment by clefebvre** [comment]
dropbox was added to the repositories today.
