### ISSUE TITLE
live-installer: l10n on stock widgets

### ISSUE THREAD

**Issue by mvdberge** [linuxmint/lmde-3-cinnamon-beta#14]
When clicking through the installation process and choosing "German" as default language, some installation translations stay in English, see attached screenshot.
![screenshot](https://user-images.githubusercontent.com/8587894/43511698-5721af8e-9579-11e8-94d2-3fc0ad8f7fec.png)

**Comment by mvdberge** [comment]
When editing the partitions, gparted is in English, should be in German.

**Comment by NikoKrause** [comment]
Regarding the picture: Is this calamares or the live-installer? Have you found other not translated things? If yes, can you post screenshots of those?

Regarding gparted: Is it English in the Live-Session (which would be normal, since the session starts in English) or is it English in your installed session?

**Comment by mvdberge** [comment]
I used the live-installer (linked on the desktop) in the live session. Yes, there've been some other mixes of German and English, I can try to post them if I do a new installation.

Within the installed system, after a reboot, gparted is correctly displayed in German.

**Comment by orcus-de** [comment]
does sound like that old unresolved lmde2 installer issue ... :-)
https://github.com/linuxmint/live-installer/issues/85

**Comment by monsta** [comment]
It's an additional issue... The mentioned one is reported at https://github.com/linuxmint/lmde-3-cinnamon-beta/issues/12.

**Comment by clefebvre** [comment]
Fixed.

Don't hesitate to help with the translations. These changes introduced new msgids: https://translations.launchpad.net/linuxmint/latest/+pots/live-installer.
