### ISSUE TITLE
live-installer: Partitioning issue

### ISSUE THREAD

**Issue by mtlhlth** [linuxmint/lmde-3-cinnamon-beta#16]
When choosing a pre-existing partition to format, and selecting a name from the drop down menu (/, /home, /boot/efi etc.), clicking on the desired partition name does not populate the box.  Partition name has to be entered manually.  When done entering the partition name, choosing the file system type and checking to format the partition, nothing happens when clicking on the OK button.  However, when closing the box using the X in the upper right hand corner, the screen updates, showing that the chosen partitions will be formatted.  Installer is then able to continue from there.

Occurred on an install to a Dell Inspiron 15 7559, with the .iso on a usb drive, in compatibility mode.

**Comment by kbd47** [comment]
Same issue as this. So used Calamares instead of the default installer. I mentioned this on the blog, but will post it here as well. Sudo live-installer output:
(main.py:2798): Gtk-CRITICAL **: gtk_entry_set_text: assertion ‘text != NULL’ failed

**Comment by DrTeeth707** [comment]
I had the same issue and found that doing the same thing by right-clicking the partition worked okay. I also had trouble getting rid of that malfunctioning dialogue box and had to go back to the previous screen.

**Comment by clefebvre** [comment]
Fixed by:

https://github.com/linuxmint/live-installer/commit/64d73ad1352e8f3eda9e8ed4e45eceae7af7dddb
https://github.com/linuxmint/live-installer/commit/d943b3a12f491c82331ae5173eab96b3804dc3c6
