### ISSUE TITLE
Screenshot tool Shutter missing some libraries

### ISSUE THREAD

**Issue by ghost** [linuxmint/lmde-3-cinnamon-beta#17]
The screenshot tool Shutter is missing some libraries to be fully functional. As the tool has not been updated since 2013 some old libraries are not available anymore in the repos.

**Symptoms**: Taking a screenshot is OK, but you cannot activate the Edit mode. The Edit button remains greyed-out.

**Fix**: Use the following method after installing Shutter:

$ wget https://launchpad.net/ubuntu/+archive/primary/+files/libgoocanvas-common_1.0.0-1_all.deb
$ wget https://launchpad.net/ubuntu/+archive/primary/+files/libgoocanvas3_1.0.0-1_amd64.deb
$ wget https://launchpad.net/ubuntu/+archive/primary/+files/libgoo-canvas-perl_0.06-2ubuntu3_amd64.deb
$ sudo dpkg -i *.deb
$ sudo apt-get --fix-broken install

This fix is the same as in the Linux Mint 19 versions.

**Comment by clefebvre** [comment]
This is upstream and should be reported to Debian directly.
