### ISSUE TITLE
gparted warning when run from USB boot

### ISSUE THREAD

**Issue by JeremyBoden** [linuxmint/lmde-3-cinnamon-beta#19]
I got a warning about "driver descriptor" when running gparted, which originats from libparted.
It says my "physical block size is 2048 bytes, but Linux says it is 512 bytes".
"Cancel" removes the warning but I wouldn't use it to create new partitions!
No mention is made of which disk the warning relates to, but both my HDD's have 4096 byte physical block sizes - and this accords with fdisk -l (which also says the USB boot stick has a 512 byte physical block size).

![screenshot from 2018-08-01 13-42-17](https://user-images.githubusercontent.com/41966643/43526634-3db47b1a-9594-11e8-8db4-9e8fb4838685.png)

**Comment by clefebvre** [comment]
Thanks @JeremyBoden, this is upstream from us and should be reported to gparted in Debian instead.

**Comment by JeremyBoden** [comment]
Apparently a known error. The USB stick was created with a program that gave the USB a blocksize of 2048 bytes instead of 512 bytes.
