### ISSUE TITLE
mintwelcome: Unnecessary section

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/lmde-3-cinnamon-beta#21]
Hi,

Could you remove unnecessary "New Feature" item from "Documentation" section on Mintwelcome.

![lmde3-mintwelcome](https://user-images.githubusercontent.com/1300133/43527405-3ae79762-95af-11e8-9d2f-73afbb639503.png)

**Comment by xenopeek** [comment]
The button links to currently non-existent page https://www.linuxmint.com/rel_cindy_whatsnew.php.

If there is no plan to have that page up for the final release, a bit of code to remove this block should be added after this block: https://github.com/linuxmint/mintwelcome/blob/master/usr/lib/linuxmint/mintwelcome/mintwelcome.py#L121

This test can be used for it:
```python3
if dist_name == "LMDE":
	# todo
```

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/mintwelcome/commit/72f33b307fefa145abd2a097d78abf795a621356
