### ISSUE TITLE
live-installer: Partition edit dialog

### ISSUE THREAD

**Issue by DrTeeth707** [linuxmint/lmde-3-cinnamon-beta#24]
When it came to format the EXT4 partition (which I created before the install with my partitioning software as always), I could not use the dialogue box that appears to tell the install to mount the partition as root, the filesystem was filled in. After much tooing and frowing, I found that I could only achieve my desired actions by using the right-click on the partition.

**Comment by ghost** [comment]
Advanced option and unallocated partition table have issues as well sort of this.
Especially advanced option crashes after setting.

**Comment by ovari** [comment]
May help find and fix: https://github.com/linuxmint/lmde-3-cinnamon-beta/issues/13#issuecomment-410490270?

**Comment by clefebvre** [comment]
Fixed by:

https://github.com/linuxmint/live-installer/commit/64d73ad1352e8f3eda9e8ed4e45eceae7af7dddb
https://github.com/linuxmint/live-installer/commit/d943b3a12f491c82331ae5173eab96b3804dc3c6
