### ISSUE TITLE
End of install

### ISSUE THREAD

**Issue by DrTeeth707** [linuxmint/lmde-3-cinnamon-beta#25]
At the end of the install I was dumped at the desktop. I was expecting the usual "to use the installed OS reboot or you can stay in the live edition" message. there was none.

**Comment by clefebvre** [comment]
Can you reproduce this again? Any error message in the output?

**Comment by xenopeek** [comment]
Was this with the default installer (icon on the desktop) or with the experimental Calamares installer in the menu? I couldn't reproduce it with the default installer. Haven't tried to other for this.

**Comment by xenopeek** [comment]
Closing this for lack of information. Can be reopened if somebody else can confirm and provide more detail.

**Comment by monsta** [comment]
I was able to reproduce this. It was a race condition between two threads.
It should be fixed now in `live-installer`:
https://github.com/linuxmint/live-installer/commit/35c2bf4cc4deb4d1d0e9802f49c34217e47963a0
https://github.com/linuxmint/live-installer/commit/908553ac1db4dfea3784ba4ac2189b99a7fa312a
