### ISSUE TITLE
No prompt to remove live media after install

### ISSUE THREAD

**Issue by mtlhlth** [linuxmint/lmde-3-cinnamon-beta#28]
At end of regular install, prompts to Continue Testing or Restart Now.  Normally, when clicking on Restart Now, the machine will go to shut down, and then prompt to remove the live media and hit Enter.  No such message  appeared after clicking on Restart Now button, and instead it immediately rebooted.

**Comment by xenopeek** [comment]
I could reproduce this issue on VirtualBox installation with the default installer (icon on the desktop), just as you described. Was your install also on a virtual machine or real hardware?

**Comment by mtlhlth** [comment]
My install was on real hardware, xenopeek.  Dell Inspiron 15 7559 laptop, i7-6700HQ processor, 16GB RAM, 1TB Mushkin SSD, GTX960m.  Installed via usb, created with USB Image Writer on LMDE2.

**Comment by ovari** [comment]
Also no prompt to remove with the Calamares Installer https://github.com/linuxmint/lmde-3-cinnamon-beta/issues/36

**Comment by clefebvre** [comment]
There's a systemd script in /sbin/live-installer-stop which runs prior to reboot.

It finds the live device by running:

`grep " /lib/live/mount/medium " /proc/mounts | cut -d' ' -f1`

**Comment by clefebvre** [comment]
And then the script checks if that device has a removable file...

`/sys/block/$(basename $device)/removable`

**Comment by clefebvre** [comment]
That script is provided by live-installer, but it's run by systemd, whether you're using live-installer, calamares or even just rebooting.

**Comment by clefebvre** [comment]
I can see it fail here on a macbook with a USB stick.

The device is detected as sdc1 instead of sdc, resulting in "removable" not being found.

**Comment by clefebvre** [comment]
In Virtualbox, it's detected as sr0 and works properly.

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/live-installer/commit/b28e2802287664baa855d8f8b1185da8361bf8b8
