### ISSUE TITLE
To base LMDE on latest Devuan code

### ISSUE THREAD

**Issue by DI555** [linuxmint/lmde-3-cinnamon-beta#29]
I would like to suggest to base LMDE on the latest Devuan code!
Thrue the all basic distros this imho is more truthfull and rightfull.
Please don't restrict this idea quite fast. It's a a very good idea ;) , and even more - it helps control over all dirty systemd functions !!!

**Comment by xenopeek** [comment]
This isn't an issue for the LMDE 3 beta so closing it here.
