### ISSUE TITLE
Watchdog did not stop on reboot

### ISSUE THREAD

**Issue by Onix60** [linuxmint/lmde-3-cinnamon-beta#30]
When i reboot my computer, this message is presented to me:

> watchdog watchdog0: watchdog did not  stop!

It stays there for one or two minutes, until the computer finally reboots.

Power off also takes forever now, however, the message is not presented then.

**Comment by xenopeek** [comment]
You can find a description of this issue and possible workarounds here: https://unix.stackexchange.com/a/249660. This issue would be specific to your motherboard (ACPI quirks and bugs on it, possibly triggered by ACPI related kernel parameters you set to fix other boot or backlight issue for example) and the Linux kernel version used. Not specific to the LMDE 3 beta so closing it here.

**Comment by Onix60** [comment]
May be, but i had no problems with my hardware on LMDE 2.
