### ISSUE TITLE
APCI Errors while booting

### ISSUE THREAD

**Issue by Rinow5** [linuxmint/lmde-3-cinnamon-beta#31]
ACPI Errors appear while booting.
Tried to modify grub by adding "acpi=off"; the outcome is that Mint doesn't start.
Is there a bug-fix?

Kind regards

**Comment by xenopeek** [comment]
ACPI errors are specific to your hardware and kernel version in use. Can be hard to figure out exactly which ACPI kernel parameters will let you work around ACPI quirks and bugs in your motherboard. Please take help from the forums ([here](https://forums.linuxmint.com/viewforum.php?f=246)) with troubleshooting on this one. For best help from others there, include the output of command `inxi -Fxz` in your topic to share basic info about your hardware.
