### ISSUE TITLE
Su broken?

### ISSUE THREAD

**Issue by fblais** [linuxmint/lmde-3-cinnamon-beta#32]
When I enter the su command in a terminal, to get root rights afterwards, it fails with an authentication error.
I don’t have any problem with sudo, so it isn’t a wrong password issue.

**Comment by xenopeek** [comment]
As per the [release notes](https://linuxmint.com/rel_cindy.php), the root account is locked by default. To unlock it run `sudo passwd root` first to set a password on it. If I do that I can run `su` as expected to become root with that password.

General recommend to use `sudo -i` to become root instead.

**Comment by fblais** [comment]
Thanks, didn't know about sudo's -i switch!
Good to know!
