### ISSUE TITLE
slow boot

### ISSUE THREAD

**Issue by mockturtl** [linuxmint/lmde-3-cinnamon-beta#34]
In `virtualbox-5.2` (virtualbox.org repo).  I deleted the default swap partition during installation.

When I start the VM, it hangs here, and times out at 90 seconds:

`A start job is running for dev-sda1.device`

[syslog](http://termbin.com/nyom)

**Comment by clefebvre** [comment]
Is the old partition still referred to in /etc/fstab?

**Comment by xenopeek** [comment]
If you're going to share contents of your /etc/fstab file, please also include output of this command run from the terminal:
```
lsblk -o +UUID
```

**Comment by kbd47** [comment]
I mentioned this issue with Debian on MX forum:
https://forum.mxlinux.org/viewtopic.php?f=108&t=45816
I would find the entry for the swap uuid in /etc/fstab and remove it or comment it out and save, then:
sudo update-initramfs -u
then reboot.

**Comment by mockturtl** [comment]
```txt
$ cat /etc/fstab
# UNCONFIGURED FSTAB FOR BASE SYSTEM
proc	/proc	proc	defaults	0	0
# /dev/sda1
/dev/sda1	swap	swap	sw	0	0
# /dev/sda2
UUID=c41dcb49-2ac9-4237-a1c7-9b653f1abe95	/	ext4	rw,errors=remount-ro	0	1
```

```sh
$ lsblk -o +UUID
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT UUID
sda      8:0    0   20G  0 disk            
└─sda2   8:2    0   20G  0 part /          c41dcb49-2ac9-4237-a1c7-9b653f1abe95
sr0     11:0    1 1024M  0 rom
```

@kbd47 

> I would find the entry for the swap uuid in /etc/fstab and remove it or comment it out and save, then:
> sudo update-initramfs -u 
> then reboot.

Perfect, thanks for the link!
