### ISSUE TITLE
chromium doesn't work

### ISSUE THREAD

**Issue by mdcll** [linuxmint/lmde-3-cinnamon-beta#35]
chromium doesn't work after install. neither run by icon or run by terminal.
By terminal the error is:
tecno@icvtecno:~$ chromium

(chromium:4743): GLib-GIO-ERROR **: Settings schema 'org.cinnamon.muffin' does not contain a key named 'button-layout'
`trap' para punto de parada/seguimiento
tecno@icvtecno:~$

**Comment by JosephMcc** [comment]
See: https://github.com/linuxmint/lmde-3-cinnamon-beta/issues/3
