### ISSUE TITLE
Secure Boot

### ISSUE THREAD

**Issue by ovari** [linuxmint/lmde-3-cinnamon-beta#37]
Could you please advise the instructions for LMDE 3 to boot with "Secure Boot" enabled? Thank you

**Comment by monsta** [comment]
Looks like Debian 9 (Stretch) doesn't support it yet, so it's better to turn it off before installing.

It might be supported in the next release, Debian 10 (Buster):
https://www.phoronix.com/scan.php?page=news_item&px=DebConf18-UEFI-SecureBoot

**Comment by clefebvre** [comment]
Thanks, a section was added on https://linuxmint.com/rel_cindy.php.
