### ISSUE TITLE
calamares: Automatic login

### ISSUE THREAD

**Issue by ovari** [linuxmint/lmde-3-cinnamon-beta#39]
How can we set LMDE to automatically login?

Thought we ticked the box when LMDE was installed to automatically login, but still asks to login.

Installation using Calamares Installer.

Thank you

**Comment by monsta** [comment]
Yes, Calamares has this issue. Autologin only works in live-installer now.

**Comment by clefebvre** [comment]
displaymanager module had to be added to exec list. Fixed for next ISO.
