### ISSUE TITLE
Missing Options from Add to Panel

### ISSUE THREAD

**Issue by rbeltz48** [linuxmint/lmde-3-cinnamon-beta#4]
The following icons are missing from Add to Panel after installing the MATE desktop on top of Cinnamon:

1. CPU Frequency Scaling Monitor
2. Trash
3. Weather Report

I believe all of these items are available in LMDE2. Thanks.

**Comment by rbeltz48** [comment]
Also, where is the Screensaver and Power Management? They should be in the Control Center and also under Preferences. Thanks.

**Comment by JosephMcc** [comment]
Is it possible you haven't installed everything? We don't ship or maintain Mate on LMDE3.

**Comment by clefebvre** [comment]
`apt install mate-desktop-environment-extras --install-recommends`

or if it's already installed:

`apt recommends mate-desktop-environment-extras`
