### ISSUE TITLE
libreoffice-gtk3 missing?

### ISSUE THREAD

**Issue by bobby285271** [linuxmint/lmde-3-cinnamon-beta#40]
`libreoffce-gnome` recommends `libreoffice-gtk3` but `libreoffice-gtk3` is not installed by default, which makes LibreOffce very ugly.

**Comment by ovari** [comment]
LMDE 3 beta includes [LibreOffice 5.2.z](https://wiki.documentfoundation.org/ReleasePlan/5.2).

Uninstalling LibreOffice 5.2.z and installing [LibreOffice Flatpak](https://flathub.org/apps/details/org.libreoffice.LibreOffice) makes it look nice on LMDE (in addition to the other features and benefits). LibreOffice Flatpak is also listed in the Linux Mint Software Manager.

Suggestion: Have [LibreOffice Flatpak](https://flathub.org/apps/details/org.libreoffice.LibreOffice) installed in the default LMDE 3 installation.

What do you think?

Thank you

**Comment by clefebvre** [comment]
Thanks @bobby285271, this is already fixed in the upcoming ISO (stable).
