### ISSUE TITLE
Uncheck GRUB in advanced mode crashes installation process.

### ISSUE THREAD

**Issue by ghost** [linuxmint/lmde-3-cinnamon-beta#42]
During installing, 
I have unchecked the GRUB installaion to /dev/sda, since I had to install LMDE 3 without GRUB.
Applied setting and then It crashes installation process.
please, see the video in my facebook from 08:10 ~ 08:50, this is a whole installation process video.
https://www.facebook.com/100022593461885/videos/287010712062042/?id=100022593461885

**Comment by xenopeek** [comment]
Unless I'm mistaken, I didn't see you mount the partitions you wanted to use at /target? AFAIK setting the mountpoint on the partitioning screen of the installer is  used _only_ for normal mode—for expert mode you must manually mount the partitions you want to use at /target.

You're notified you have to do this right after clicking the expert mode button:
![screenshot](https://i.imgur.com/VRDVH7x.png)

And reminded on the summary screen:
![screenshot](https://i.imgur.com/cgn7g2S.png)

When you mount no partitions at /target, expert mode has nothing to install.

**Comment by ghost** [comment]
@xenopeek I have already mounted to root (/) to /dev/sda11 
You can see it on video 07:20
so that, it means another bug itself might be sort of mounted but not not affected to system.
and also this is not the case I think though, I don't think it is normal that brings crash installation process just by the reason missing process, there should be instruction or notification to users I think, not a crash.

**Comment by xenopeek** [comment]
At 7:20 in the video it shows you've set mountpoints for normal mode installation. Those mountpoints **aren't** used in expert mode installation. You're misunderstanding the instructions.

In expert mode you **must** manually mount partitions you want to use for your installation in the /target directory. I.e., with `mount` commands on the terminal.

The installer instructs you to mount destination partitions manually under /target and then reminds you of the same on the summary screen. You ignored those instructions and thus the installer aborts (doesn't crash) when you proceed from the summary screen.

During installation in expert mode the installer will twice show you instructions like the above, telling you to do something on the terminal before proceeding. As this is expert mode it only tells you what to do—not how to do it.

**Comment by ghost** [comment]
Alright, it means expert mode need to pre-proceed in terminal to mount /target not GUI.
I don’t agree with this concept that process for advanced mode but I understand it and will follow Linux Mint team’s policy.
But, I think there should be a dialog window to alert and to ask to users, like me getting in expert mode eventually, whether choosing abort the process or going back to normal mode.
