### ISSUE TITLE
network broadband device invisible

### ISSUE THREAD

**Issue by PKscrat** [linuxmint/lmde-3-cinnamon-beta#43]
The device selection field for the mobile network connection is empty, preventing the configuration.
![2018-08-06 11-05-55](https://user-images.githubusercontent.com/22936406/43717137-dc6106fc-9986-11e8-9076-58ae0d980351.png)

Note: It works perfectly under Linux Mint Ubuntu Edition.

For information the device works:
![2018-08-06 14-46-53](https://user-images.githubusercontent.com/22936406/43717680-8e732022-9988-11e8-8cc7-9af5a435ae4f.png)

Here is what is displayed when using another distribution:
![2018-08-09 17-40-40](https://user-images.githubusercontent.com/22936406/43995246-df337608-9daa-11e8-9460-78a4a0e69d1a.png)

**Comment by clefebvre** [comment]
Hi @PKscrat,

This is upstream from us. The "Set up a Mobile Broadband Connection" dialog isn't part of Cinnamon, it's a part of network-manager.

**Comment by clefebvre** [comment]
It could be an upstream issue in Debian's network-manager, or it could be an issue with the detection of your device. I would suggest to check dmesg and system logs to make sure the system sees this device properly. I know it works (from the screenshot of the network applet) but maybe it's not recognized as the right device type?
