### ISSUE TITLE
Wi-fi refuses to connect

### ISSUE THREAD

**Issue by ghost** [linuxmint/lmde-3-cinnamon-beta#45]
LMDE3 sees my Linksys WUSB54GC v1 802.11g USB Adapter [Ralink RT73] but will not connect to my local network. Drivers are not needed for this device as it is quite old at this point and just works with most other distros I've tried. Since the device seems to be working properly, it may be that LMDE3 somehow can't deal with the WPA, WPA2 encryption? Please let me know how I can help to provide more specific information. It asks for the password, I put it in and then it just doesn't connect.

**Comment by clefebvre** [comment]
Hi,

Check the system logs. The device is likely to log disconnects or failure to connect there.

**Comment by fblais** [comment]
Solution is here:
https://github.com/linuxmint/lmde-3-cinnamon-beta/issues/22

**Comment by ghost** [comment]
Hi Clem,

I am attaching the pertinent logs that show something about the LAN. 

hi fblais,

That solution was a bit confusing... 

Here are the log entries that concern Wi-Fi:

[lmde-wifi-errors.txt](https://github.com/linuxmint/lmde-3-cinnamon-beta/files/2267075/lmde-wifi-errors.txt

**Comment by fblais** [comment]
Confusing?
You just need to edit a file and add two lines, if the [device] section isn't already present in your file:

sudo xed /etc/NetworkManager/NetworkManager.conf

add the line(s):

[device]
wifi.scan-rand-mac-address=no

Save the file, then simply reboot and that's it.

**Comment by ghost** [comment]
fblais,

Thanks. It does work. Editing the file was not the confusing part... Why I need to edit this file to get this adapter to work when it works seamlessly on every other distro I have ever tried for more than five years is confusing. :)

**Comment by fblais** [comment]
I understand.  :)
Debian’s wireless problems have been a plague for many people, me included.
I also had to use that patch to get connected.

**Comment by ghost** [comment]
fblais,

Upstream... I see. Thank you again. I will attempt another hardware install soon. :)

**Comment by trytip** [comment]
@EzeeLinux 
my wifi works flawlessly in arch linux, mint 17.3 and 19 but in LMDE3 it would not connect.  it is detected and my wifi led is on but i get authentication failure.  i am using gufw, not sure if that makes a difference.  i just commented out the lines in `/etc/NetworkManager/NetworkManager.conf` which is present in mint19 also and wifi stopped working. issuing `systemctl restart NetworkManager` brought it back after uncommenting the lines
```
[device]
wifi.scan-rand-mac-address=no
```
try commenting these lines in your mint19 to test it.
