### ISSUE TITLE
Bluetooth Mouse Problems

### ISSUE THREAD

**Issue by darethehair** [linuxmint/lmde-3-cinnamon-beta#46]
Dell bluetooth mouse works fine with previous versions of Linux Mint, including LMDE2.  With LMDE3, pairing and operation after restart initially works fine, but within a few minutes it stops responding -- even though the bluetooth applet may indicate that the mouse is still 'connected'.  Attempts to dis-connect and re-connect have resulted in the applet freezing.  As i write this, the applet indicates that the mouse is 'disconnected', but it refuses to obey my request to 'remove device' so that I can try to add it back again.

**Comment by clefebvre** [comment]
Hi @darethehair,

That looks upstream from us. If gnome-bluetooth isn't working properly you can try blueman as an alternative.
