### ISSUE TITLE
mintinstall 7.9.5

### ISSUE THREAD

**Issue by callagg2** [linuxmint/lmde-3-cinnamon-beta#47]
With linux mint 19 (Cinnamon 3.8.8) , after i install an application on mintinstall, the launch button is green while the remove button is red.
The same is not happening with LMDE!

**Comment by JosephMcc** [comment]
Need more info. For example, what theme are you using? Did you change it from the default one?

**Comment by callagg2** [comment]
Joseph, yes i did change Themes.

Window borders = Mint-Y-Dark
Icons = Mint-X-Teal
Controls = Mint-x-Teal
Mouse Pointer = DMZ-Black
Desktop = Mint-Y-Dark

Does this help?

**Comment by callagg2** [comment]
not sure if this helps
 inxi -G
Graphics:  Card: NVIDIA C79 [GeForce 9400M]
           Display Server: X.Org 1.19.2 drivers: nvidia (unloaded: modesetting,fbdev,vesa,nouveau)
           Resolution: 1280x800@61.18hz
           GLX Renderer: GeForce 9400M/integrated/SSE2
           GLX Version: 3.3.0 NVIDIA 340.106

**Comment by JosephMcc** [comment]
Yep. The Mint-X control themes have never supported the .suggested-action and .destructive-action style classes. That's why the buttons aren't colored. The default Mint-Y theme does.
