### ISSUE TITLE
In virtualbox : super slow kernel update + pb of color on desktop background

### ISSUE THREAD

**Issue by flacasa** [linuxmint/lmde-3-cinnamon-beta#48]
Hi,
I installed LMDE3 beta in a virtualbox for testing.
I installed the vbox gust additions, gave access to hardware acceleration and 2G of RAM, which should be well enough to run Cinnamon. It does run very smoothly and is very nice.
However there are minor graphical problems : whenever I boot, the desktop background has changed color. I use the default wallpaper by Bookwood, and the Mint logo is a saturated yellow instead of green. See [this screenshot](https://www.normalesup.org/~lacasa/LMDE3-VirtualBox_wallpaper.png).Changing the background to another and coming back fixes the issue.
Also when hovering the mouse over the Mint menu, the grey highlighting is strange, see [this screenshot](https://www.normalesup.org/~lacasa/LMDE3-VirtualBox_mintmenu.png).

Finally the perhaps more important issue is that when I updated the kernel today to 4.9.110-3, the update manager took 30 mins to do so. The process was stuck at unpacking the linux headers, images etc. Firing top showed that synaptic was using only <1% CPU. It finally completed and works after reboot, but this update time is far too long for daily use.

**Comment by clefebvre** [comment]
Hi @flacasa,

These all look like Virtualbox issues. There's not much we can do other than suggest you report the issues to them directly or switch to real hardware to get better GPU rendering and CPU usage.
