### ISSUE TITLE
PrtScreen key does not bring up ScreenSave

### ISSUE THREAD

**Issue by jtcraigjr** [linuxmint/lmde-3-cinnamon-beta#49]
PrtScn is not functioning for me LMDE-3 Cindy
no issues with any other Mint version.

**Comment by mexsudo** [comment]
same here: PrtScn is not functioning for me LMDE-3 Cindy
no issues with any other distros

**Comment by Onix60** [comment]
same here: PrtScn is not functioning for me LMDE-3

**Comment by clefebvre** [comment]
ok that's Debian's version of gnome-screenshot, it's never been patched. Backporting Mint 18's version will fix the issue.

I also noticed gnome-power-statistics was missing, we'll add that in the next ISO as well.

**Comment by clefebvre** [comment]
Fixed with gnome-screenshot 1:3.18.0+2linuxmint3.
