### ISSUE TITLE
Package Updater / Timeshift problem

### ISSUE THREAD

**Issue by JeremyBoden** [linuxmint/lmde-3-cinnamon-beta#5]
The package updater REQUIRES that Timeshift be configured.
However, Timeshift requires a spare partition be set-up (which isn't done as part of the install).
This prevents me using the update icon if I don't want to use Timeshift.
I already have alternate backup strategies in place.

**Comment by clefebvre** [comment]
No, you can use timeshift in your / partition.
Also, you can ignore the warning and disable it in the Update Manager preferences.
