### ISSUE TITLE
mintupdate blacklist not work

### ISSUE THREAD

**Issue by Onix60** [linuxmint/lmde-3-cinnamon-beta#50]
After adding the program to the blacklist after a time again offers to update.

**Comment by monsta** [comment]
Yes, I remember this happened before: https://github.com/linuxmint/mintupdate/issues/259
For some reason it didn't happen in Ubuntu-based Mint editions...

**Comment by clefebvre** [comment]
We're talking about mintupdate run as user, in graphical mode here, right?

**Comment by Onix60** [comment]
Yes.

**Comment by rbeltz48** [comment]
Same issue here on my Lenovo Thinkpad T400. Though shown in blacklist, Update Manager still shows that package to update.

**Comment by clefebvre** [comment]
Can we get the gsettings output for the blacklist? and the output of checkAPT.py here?

**Comment by clefebvre** [comment]
OK I can reproduce it. It's down to sudo (run in a different mode in Debian) and access to gsettings. CheckAPT is basically looking at root's blacklist instead of your own.

**Comment by clefebvre** [comment]
One solution would be to split checkAPT in two, and separate cache updates with the gathering of the updates list. That's quite a change in design though, it won't happen right now.

I'll create an issue in mintupdate and mark this for implementation in the roadmap.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintupdate/issues/379
