### ISSUE TITLE
Choix de la langue à installer

### ISSUE THREAD

**Issue by Phil995511** [linuxmint/lmde-3-cinnamon-beta#51]
A l'installation il n'y a pas d'option pour configurer la langue à installer en "Français-suisse" (clavier qwertz) on est obligé de choisir "German-Fr". Par la suite, lors de l'installation, au moment du partitionnement des disques, les bouton du bas sont en allemand et non pas en français ce qui n'est franchement pas pratique du tout quand on ne parle pas allemand...

**Comment by clefebvre** [comment]
Le bug relatif aux boutons du bas (et aussi aux boutons des fenetres de dialogue) est maintenant resolu, cela ne se reproduira plus dans la version stable.

Pour ce qui est de la liste des locales en revanche, cela est au dessus de nous (upstream) et directement maintenu par Debian.

**Comment by clefebvre** [comment]
Petite rectification apres test.

Vous pouvez choisir la language "French - Switzerland" et pour le clavier la disposition "German (Switzerland)", variante "French (Switzerland)".

Les boutons du bas (et des fenetres de dialogues) on ete corriges. Le nouvel installeur est disponible dans les depots mais nous attendons encore les nouvelles traductions. Tout ceci sera pret pour le prochain ISO.
