### ISSUE TITLE
Driver graphique

### ISSUE THREAD

**Issue by Phil995511** [linuxmint/lmde-3-cinnamon-beta#52]
Il n'y a malheureusement pas de possibilités d'installer un driver graphique avec facilité (pas d'option existante dans "Paramètres Systèmes"). Une installation facilitée des drivers graphiques Nvidia / Intel / ATI (AMD) ainsi que leur mise-à-jour "automatisée" serait plus que la bien venue. Il est a remarquer qu'en machine virtuelle la résolution maximale est de 1024x768 ce qui offre une fenêtre d'affichage vraiment très petite, cela surtout avec un écran 2K ou plus...

**Comment by clefebvre** [comment]
Desoles, il n'est pas prevu de porter mintdrivers vers Debian pour le moment.
