### ISSUE TITLE
Power Manager Applet

### ISSUE THREAD

**Issue by callagg2** [linuxmint/lmde-3-cinnamon-beta#54]
Default theme installed.
The power manager applet keeps disappearing and being replaced by the "keyboard backlight" applet.

**Comment by mtwebster** [comment]
Hi,

When this happens, is the 'csd-power' process still running?
```
ps -A | grep csd-power
```

Whether or not it's running, can you try running that in debug mode:
```
sudo killall csd-power # do this twice, if csd-power showed up in the process list, otherwise skip this step.
G_MESSAGES_DEBUG=all csd-power --verbose
```

then restart cinnamon and wait for the problem to occur.

It sounds like what's really happening is the applet is losing contact with the power manager (csd-power) in cinnamon-settings-daemon.  It only looks like a different applet because most of the info isn't available.

**Comment by callagg2** [comment]
Yes, it's still happening.
Running that command, i get 

G_MESSAGES_DEBUG=all csd-power --verbose
(csd-power:1483): power-plugin-DEBUG: Starting power manager
(csd-power:1483): power-plugin-DEBUG: Adding suspend delay inhibitor
(csd-power:1483): power-plugin-DEBUG: Adding lid switch system inhibitor
(csd-power:1483): power-plugin-DEBUG: tooltip: 
(csd-power:1483): power-plugin-DEBUG: adding /org/freedesktop/UPower/devices/line_power_ADP1 with state unknown
(csd-power:1483): power-plugin-DEBUG: Registered client at path /org/gnome/SessionManager/Client30
(csd-power:1483): power-plugin-DEBUG: System inhibitor fd is 15
(csd-power:1483): power-plugin-DEBUG: System inhibitor fd is 14
(csd-power:1483): power-plugin-DEBUG: setting up blank callback for 1800s
(csd-power:1483): power-plugin-DEBUG: idle dim set with timeout 90
(csd-power:1483): power-plugin-DEBUG: Setting dim idle timeout: 90s

i wish i could be of more help...

**Comment by mtwebster** [comment]
Ah wait, is this a desktop pc?  The applet is designed to behave as you're describing when there are no battery devices.  If there are no devices that have a brightness control, the entire applet hides.

**Comment by callagg2** [comment]
no, its a 2009 macbook pro laptop... 
irrespective of whether the charging cable is in or not, this happens.

**Comment by mtwebster** [comment]
Ah, well, let's check something else.

install d-feet (`sudo apt-get install d-feet`) and run it (it installs to the menu)

Once the program appears, make sure 'System Bus' is selected at the top, and type 'upower' in the search box.  You should see an 'org.freedesktop.UPower' entry.  Select it, then look in the right view, and see what devices show up.  For instance, on my laptop here, I have the following:
![image](https://user-images.githubusercontent.com/262776/44237397-504d6200-a17e-11e8-95ce-e6245d6a209c.png)

This is the service that ultimately provides device info for the power applet.  Do any battery devices show up there?

**Comment by callagg2** [comment]
i see 
/org/freedesktop/UPower
/org/freedesktop/UPower/KbdBacklight
/org/freedesktop/UPower/Wakeups
/org/freedesktop/UPower/devices/DisplayDevice
/org/freedesktop/UPower/devices/line_power_ADP1

that's all

**Comment by callagg2** [comment]
Ordinarily i would say maybe the battery is just dodgy, but while it only charges up to 86% - when the display does show the percentage :-) the lap top will work off battery for 2-3 hours before dying around 12%.

**Comment by callagg2** [comment]
and today without doing anything other than reboot, the percentage is back

G_MESSAGES_DEBUG=all csd-power --verbose
(csd-power:1597): power-plugin-DEBUG: Starting power manager
(csd-power:1597): power-plugin-DEBUG: Adding suspend delay inhibitor
(csd-power:1597): power-plugin-DEBUG: Adding lid switch system inhibitor
(csd-power:1597): power-plugin-DEBUG: tooltip: 
(csd-power:1597): power-plugin-DEBUG: adding /org/freedesktop/UPower/devices/line_power_ADP1 with state unknown
(csd-power:1597): power-plugin-DEBUG: adding /org/freedesktop/UPower/devices/battery_BAT0 with state discharging
(csd-power:1597): power-plugin-DEBUG: updating because we added a device
(csd-power:1597): power-plugin-DEBUG: printing composite device
(csd-power:1597): power-plugin-DEBUG: time zero, falling back to percentage for battery
(csd-power:1597): power-plugin-DEBUG: Registered client at path /org/gnome/SessionManager/Client30
(csd-power:1597): power-plugin-DEBUG: System inhibitor fd is 14
(csd-power:1597): power-plugin-DEBUG: System inhibitor fd is 13
(csd-power:1597): power-plugin-DEBUG: setting up blank callback for 1800s
(csd-power:1597): power-plugin-DEBUG: idle dim set with timeout 90
(csd-power:1597): power-plugin-DEBUG: Setting dim idle timeout: 90s
(csd-power:1597): power-plugin-DEBUG: updating because /org/freedesktop/UPower/devices/battery_BAT0 changed
(csd-power:1597): power-plugin-DEBUG: using original device as only one primary battery
(csd-power:1597): power-plugin-DEBUG: /org/freedesktop/UPower/devices/battery_BAT0 state is now discharging
(csd-power:1597): power-plugin-DEBUG: using original device as only one primary battery
(csd-power:1597): power-plugin-DEBUG: using original device as only one primary battery
(csd-power:1597): power-plugin-DEBUG: using original device as only one primary battery
(csd-power:1597): power-plugin-DEBUG: using original device as only one primary battery
(csd-power:1597): power-plugin-DEBUG: using original device as only one primary battery
(csd-power:1597): power-plugin-DEBUG: using original device as only one primary battery
(csd-power:1597): power-plugin-DEBUG: using original device as only one primary battery
(csd-power:1597): power-plugin-DEBUG: using original device as only one primary battery
(csd-power:1597): power-plugin-DEBUG: using original device as only one primary battery
(csd-power:1597): power-plugin-DEBUG: got filename: battery-full-symbolic;gpm-battery-080;battery-full;

you might as well close this bug, because this laptop has a mind of its own, can't be fixed.
