### ISSUE TITLE
Live Boot

### ISSUE THREAD

**Issue by Chrislmde** [linuxmint/lmde-3-cinnamon-beta#56]
Not exactly a bug, but may cause confusion for any new user... 

There's no indication of progress when booting the LiveCD/USB - you're left staring at the Linux Mint Logo. As this can take a while on some hardware, some users could think the loading process has crashed. It seems to me that some feedback like the usual scrolling dots, or even text, would be better.

**Comment by clefebvre** [comment]
One can use the left/right arrows to access the text mode. This is a plymouth feature.

I agree with the dots, although we've no plans to path plymouth in Debian atm.
