### ISSUE TITLE
Battery indicator

### ISSUE THREAD

**Issue by theoar** [linuxmint/lmde-3-cinnamon-beta#57]
Default battery indicator applet (power@cinnamon.org) doesn't show battery stats after rebooting system. It shows only when I change the brightness of my screen using keyboard keys. After that applet displays remaining time but it dosen't update it. So for whole time I have the same amount of battery percentage usage displayed in applet. 

After rebooting the system I don't have any battery visible in Power Management. The battery shows up only when I change the brightness of my screen. 

Before changing brightness:

> /sys/class/power_supply$ ls
> AC

After changing brightness:
> /sys/class/power_supply$ ls
> AC BAT0

 When battery is visible in the Power Management app. its status is refreshed every time I open this app but it doesn't affect to the applet (it still display the same values). Changing the name of the battery and closing the application updates the values in the applet.

**Comment by jtcraigjr** [comment]
The indicator is only showing percent of charge on my LMDE3-Cindy, and the hardware name also.

see image https://i.imgur.com/roe0zVS.png

**Comment by theoar** [comment]
I know what it shows but for me it looks like:

After reboot (before changing brightness by keyboard function keys)
![1](https://user-images.githubusercontent.com/6282165/44100617-c192eede-9fe5-11e8-8b6d-96d41f7db062.png)
![2](https://user-images.githubusercontent.com/6282165/44100619-c1bcde88-9fe5-11e8-89da-188854b9273b.png)


After reboot (after changing brightness by keyboard function keys)
![3](https://user-images.githubusercontent.com/6282165/44100622-c2850fc0-9fe5-11e8-9d3e-3cc49a5388a6.png)
![4](https://user-images.githubusercontent.com/6282165/44100627-c3c8bc92-9fe5-11e8-9c92-d09206fe8fc8.png)

As you can see after reboot the applet displays nothing and the battery isn't visible in the Power Management. Even when the battery is visible its status isn't updated so for the whole time it will be showing the same percent of charge.

**Comment by clefebvre** [comment]
Hi,

This looks like a kernel issue with your hardware. The fact that the battery is absent from /sys/class/power_supply indicates the issue isn't with the applet but with the system.
