### ISSUE TITLE
LMDE3-Cindy can't turn off Desktop sorting in Desktop Preferences

### ISSUE THREAD

**Issue by jtcraigjr** [linuxmint/lmde-3-cinnamon-beta#58]
Desktop defaults to always placing folders/files sorted in Alphabetical order,  left side, top to bottom.
I don't like that feature, I want to turn off forced placement of files just like I can in 18.3 Cinnamon

**Comment by clefebvre** [comment]
Sorry I can't reproduce this issue.

**Comment by mtwebster** [comment]
right-click the desktop, turn off Desktop->Auto Arange?

**Comment by jtcraigjr** [comment]
Right Click just brings up the same Menu as Preferences Desktop, and AutoArrange is not there, like it is in 18.3

Why close this before I have a change to report back?
Sorry, missed the 2nd Desktop down at the bottom of the Right Click menu, that should be move up above.
