### ISSUE TITLE
Samba sharing very broken

### ISSUE THREAD

**Issue by qbicdesign** [linuxmint/lmde-3-cinnamon-beta#59]
In Nemo it should be possible to share a folder by right clicking and selecting "Sharing options" then setting the share pareameters.
However, instead the sharing dialogue appears with a light blue notice (with white text, making it pretty hard to read) saying "Samba needs to be installed, and your user account needs to join the 'sambashare' group" - next to it is a button "Install".
If you click the button the following message appears "Something went wrong. You may need to install samba and add your user to the 'sambashare' group manually."

I manually installed samba and added the user to the group. The same error messages still appear as if I still don't have samba installed. 

Samba should be installed correctly by default and this feature needs to work out of box. I don't really understand why samba and all related components for this feature are not dependencies of Nemo.

FYI the same feature works perfectly out of box in Mint 18 cinnamon.

**Comment by clefebvre** [comment]
I think it's probably because of sessioninstaller missing in Debian. This is the component responsible for distro-agnostic package installs, used by Cinnamon, in Ubuntu: https://packages.ubuntu.com/bionic/sessioninstaller.

**Comment by clefebvre** [comment]
What nemo-share checks is:

- The presence of /usr/sbin/smbd (and the fact that it's executable)
- The presence of "sambashare" in the output of "id -Gn your_username"

We can't expect Samba to work out of the box, that's never been the case upstream and to be honest it's gotten worse over the years. We also ship without it, not only because it's not something that works well for everybody just by installing it, but also because it requires open ports and slows the boot sequence, so for people who don't need it, there's no reason for it to be there.

**Comment by qbicdesign** [comment]
In that case wouldn't it make more sense to bundle Nemo in LMDE3 without the nemo-share package (which clearly requires samba)?

**Comment by qbicdesign** [comment]
wait ... after installing samba, /usr/sbin/smbd doesn't exist. however /usr/sbin/samba does.
so.... Nemo is checking for something which will never exist without a whole bunch of hacking around.
That doesn't sound sensible...

**Comment by clefebvre** [comment]
https://packages.debian.org/stretch/amd64/samba/filelist contains /usr/sbin/smbd

**Comment by clefebvre** [comment]
nemo-share without samba isn't totally useless, it hints at what needs to be done and is able to do automatically in the presence of sessioninstaller.

**Comment by qbicdesign** [comment]
LMDE offered me an upgrade to samba, which I have now done.
smbd is running and the file  /usr/sbin/smbd /usr/sbin/smbd - it was just hidden. 
It was executable too

For some reason my user didn't get allocated to the group correctly, so i did that again and restarted smbd, now the message has gone away, but replaced by:

'net usershare' returned error 255: net usershare: cannot open usershare directory /var/lib/samba/usershares. Error Permission denied
You do not have permission to create a usershare. Ask your administrator to grant you permissions to create a share.

Seems like a common error and I'm searching a solution.
Just didn't expect to be jumping through this many hoops for something so basic as a fileshare...

**Comment by clefebvre** [comment]
Well, sessioninstaller would have helped here. In Mint it basically installs samba and adds the group for you. That said, samba doesn't always work out of the box and some of the samba tools packaged by Debian just simply don't work anymore.

**Comment by TiredOfWindows** [comment]
I had the same problem with Samba sharing and fixed it by unhiding "/var/lib/samba/usershares" and changing the permissions. Samba doesn't seem to be able to find it and/or write to it. Open the "/var/lib/samba" folder as "root". Navigate to the "/var/lib/samba/usershares" folder and right click on it. Click on "properties" open the "permissions" tab. Leave the "Owner" as "root" with "folder access" as "create and delete files", change the "group" to "sambashare" with "folder access" as "create and delete files". The last "folder access" should be set to "none". Exit the window, restart the computer and try sharing your folder again.
