### ISSUE TITLE
Installer needs a propper setup for btrfs-root-fs (using ubuntu-like  /@ subvolume) => timeshift

### ISSUE THREAD

**Issue by orcus-de** [linuxmint/lmde-3-cinnamon-beta#61]
The installer does not setup and use a /@ subvolume for a btrfs-root fs.
This is seemingly required for timeshift to work - as otherwise one cant create/user btrfs snapshots with it.
----------------------
Workaround at the moment.

 setting up a btrfs-partition + creating the expected /@ subvolume there
 create /target on live-mint and mount the subvolume (and not the btrfs-partition itself) there
 sudo mount /dev/vdaX btrfs rw,subvol=@ /target
 mounting additional partitions (like boot, home - both ext4) at /target/mnt and /target/home, ...

Doing an expert-setup and let it proceed until the paused-message does show up:

setting up /target/etc/fstab 
#... other mounts ...
UUID=asfjasjkfalösdfjalsfjlas     /  brtfs   rw,subvol=/@     0      0
...
continue setup  (smaller bug: the "installation has finished - do you want to continue or reboot"-Msg  does show up  , blocking the paused-message  (I did not test if choosing reboot would have aborted the expert-setup entirely)   -> did choose to continue, after that the pause-msg is accessible again)

Final checks before reboot:

To my great surprise after checking /boot/grub/grub.cfg  the required entry
"rootflags=subvol=@"
has already been there :-)

Rebooting system:  / is mounted from the /@ subvolume + timeshift starts working as expected.

**Comment by orcus-de** [comment]
shh... what I'v forgotten  (I've used the deb-file from the intaller.zip (from issue-thread https://github.com/linuxmint/lmde-3-cinnamon-beta/issues/13)

**Comment by MarkusKull** [comment]
Independently tried to get timeshift+btrfs to work before upgrading from LMDE2 to LMDE3, but btrfs was highly unstable. Converted ext4 to btrfs with no issues, but with further changes lots of io-errors in **both** LMDE2 and live-LMDE3 with mounted btrfs-partitions. Interestingly only new files were affected, but existing snapshots were ok. I could reproducibly copy a file to btrfs and sha256sum differed, content was zeroed. Lots of warnings in /var/log/messages about accesses after disk-end. So, two kernels were affected and memtester shows nothing?

In the end, i rolled back to ext4 without further issues. For now, btrfs is considered unsafe at any speed.

**Comment by clefebvre** [comment]
I need to close this as the BETA is finished. @orcus-de if you can, would you turn this into a pull request against live-installer?
