### ISSUE TITLE
lmde 3 beta doesn't install/ run as live cd

### ISSUE THREAD

**Issue by drnaseeb** [linuxmint/lmde-3-cinnamon-beta#62]
When Start lmde 3 beta is chosen, it shows:
(initramfs) mount: mounting /dev/loop0 on //filesystem.squashfs failed: Invalid argument
Can not mount /dev/loop0 (/live/medium//live/filesystem.squashfs) on //filesystem.squashfs

**Comment by clefebvre** [comment]
Closing as the cause wasn't found and the BETA is now finished.
