### ISSUE TITLE
Bleachbit (root) will not accept my password.

### ISSUE THREAD

**Issue by mexsudo** [linuxmint/lmde-3-cinnamon-beta#64]
Bleachbit will run as user, no password... no problem.

Bleachbit (root) will not accept my password.

two other users confirmed the same

**Comment by clefebvre** [comment]
I'm sorry, this is upstream from us and should be reported to Debian directly.

**Comment by mexsudo** [comment]
I don't understand your term "upstream"
bleachbit works as expected in Debian

bleachbit works as expected in SalentOS (also Debain based)

**Comment by monsta** [comment]
Ah, bleachbit still uses gksu in Debian Stretch:

```
$ cat /usr/share/applications/bleachbit-root.desktop | grep Exec
TryExec=su-to-root
Exec=su-to-root -X -c bleachbit
```
This requires root password, which [isn't set](https://linuxmint.com/rel_cindy.php) in LMDE 3.

Try `gksudo bleachbit`, it will ask your password.

**Comment by mexsudo** [comment]
I suggest that a root password be required for LMDE

**Comment by mexsudo** [comment]
I set a password for root
Bleachbit (root) now works as expected
