### ISSUE TITLE
CPU treashold while installing Ruby

### ISSUE THREAD

**Issue by mrgwart** [linuxmint/lmde-3-cinnamon-beta#65]
The system halt with a CPU temperature threashold when installing Ruby from the Terminal. During installation, application as hang. 

This problem isn't happening on Linux Mint Ubuntu version.

Compute model: Acer Aspire 8735G-6472
Intel Core 2 Duo processor P7450 2.13Mhz 1066 MHz FSB
Nvigia GeForce GT240M
4GB Memory

**Comment by clefebvre** [comment]
This is upstream from us and should be reported to Debian directly.
