### ISSUE TITLE
Installer ignores language, uses location for partition interface

### ISSUE THREAD

**Issue by jeffmcneill** [linuxmint/lmde-3-cinnamon-beta#67]
I select English US for language, and also keyboard layout, and a US timezone for location, and then the partition screen displays menu items in Thai. (I am at a Thailand IP address). 

Expected behavior: Partition interface screen should show language selected in previous scree.

Actual behavior: Partition interface screen shows language based on current IP address.

**Comment by monsta** [comment]
It's https://github.com/linuxmint/lmde-3-cinnamon-beta/issues/12 and it's fixed in the latest installer. Try upgrading it first: `apt install live-installer`.
