### ISSUE TITLE
No Internet Connection

### ISSUE THREAD

**Issue by trytip** [linuxmint/lmde-3-cinnamon-beta#7]
downloaded lmde-3-cinnamon-64bit-beta.iso.torrent then installed using the installer on desktop (needs a lot of work,  mounting points do not exit when you click OK, had to be really certain that my root/swap/home is where i want it to be) but there is no internet connection in live or in installed system.  my wifi adapter is recognized by ubuntu 12.04 live so i don't need any drivers.  trying to connect killed my router (had to restart router connection since it lowered my speed to -2Mbps and became very unstable connection)  

delete mint19 cinnamon and did clean install in same partition, was able to restore mint19 using timeshift. tried lmde3 live again, with no internet connection. something wrong with DHCP ?

`nm-applet-Message: No keyring secrets found for Auto *******/802-11-wireless-security; asking user.
Nemo-Share-Message: Called "net usershare info" but it failed: 'net usershare' returned error 255: mkdir failed on directory /var/run/samba/msg.lock: Permission denied
net usershare: cannot open usershare directory /var/lib/samba/usershares. Error No such file or directory
Please ask your system administrator to enable user sharing.

lsusb: Qualcomm Atheros Communications AR9271 802.11n 
Driver: ath9k_htc

**Comment by fblais** [comment]
This is related to Debian itself.
It doesn’t include non-free network drivers by default I think.
The most annoying thing in Debian IMHO.

**Comment by clefebvre** [comment]
This is upstream indeed.

Note: We do ship and activate broadcom drivers in LMDE.
