### ISSUE TITLE
Wireless & Install Problems With 8/31 Version of LMDE 3

### ISSUE THREAD

**Issue by rbeltz48** [linuxmint/lmde-3-cinnamon-beta#70]
In live mode the LMDE 3 Beta connects fine and stays connected. The 8/31 LMDE 3 version in live mode has trouble connecting. When it finally connects it then disconnects. I have also not been able ti install the 8/31 version but the Beta installs just fine. I have never seen issues like this happen in a non-Beta version before, whether LMDE or the regular Mint releases. I use Lenovo Thinkpads.

**Comment by clefebvre** [comment]
Hi @rbeltz48,

Please use the forums to seek assistance or the troubleshooting guide to identify an issue http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/.

This repository was set up for the BETA and is no longer active.
