### ISSUE TITLE
Fcitx does not work (qimpanel not visible)

### ISSUE THREAD

**Issue by harlekin777** [linuxmint/lmde-3-cinnamon-beta#72]
Title says it all. In LMDE 3 Qimpanel does not show up after activating Fcitx and typing, therefore making Fcitx unusable. Qimpanel is also invisible in fcitx-qimpanel-configtool. It does work in LM 19.
I know, LMDE 3 is no more Beta and this place outdated, but there is no appropriate category for reporting this bug.

**Comment by harlekin777** [comment]
I would like to add that Fcitx works without any issues in Debian 9. This is not a Debian bug.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintlocale/issues/61
