### ISSUE TITLE
LMDE3 boot after installing packages

### ISSUE THREAD

**Issue by JJBabs** [linuxmint/lmde-3-cinnamon-beta#73]
Good Day. LMDE3, installed on an older disk, after performing and update and installing a script for my trackball I reboot and install additional packages. After installing the packages I do a reboot and it Hang on boot, giving 2 messages “A start job is running for device initialisation” and “Looking for device (UUID)” They time out and I am dropped to an Emergency shell, but I can’t do anything.
So, I used a much newer disk; same procedure, same result.
I set the disks up with a ~30G partition for the system files, and the remainder of the disk as /home. SDA1 mounts and loads just fine, SDA2 is lost somewhere. Any ideas?

**Comment by clefebvre** [comment]
Hi @JJBabs,

Please use the forums to seek assistance or the troubleshooting guide to identify an issue http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/.

This repository was set up for the BETA and is no longer active.
