### ISSUE TITLE
Gdebi doesn't appear in search or Menu

### ISSUE THREAD

**Issue by kbd47** [linuxmint/lmde-3-cinnamon-beta#8]
Even though it is installed it does not show up in Menu or a search of the Menu.
If you launch gdebi-gtk from the terminal it is not fully functional. Yet you can right-click on a deb file and gdebi will launch and works.

**Comment by clefebvre** [comment]
Hi,

This is the expected behaviour. It works like a mime handler, if you launch it without a file it just shows no particular content. There's no reason to launch it from the menus.
